### ISSUE TITLE
[Documentation]

### ISSUE THREAD

**Issue by Darkcast** [crazywifi/OKCupid_LIKES_Restriction_Bypass#2]
Hey man great work, I was just wonder if wouldnt be too much to ask could you please add the way you got the Cookie1 , Cookie2 =  and the uthorization2
thanks.

**Comment by crazywifi** [comment]
I will check and update it. Give me some time.

**Comment by Darkcast** [comment]
Great thank you also, I made some changes to the script so it uses a list of cheese pick up lines 😂️

**Comment by crazywifi** [comment]
Great! .. Share it with me :)

**Comment by crazywifi** [comment]
> Great thank you also, I made some changes to the script so it uses a list of cheese pick up lines 😂️

I think, my script now no ore working. Because of the website response code changed.

**Comment by Darkcast** [comment]
ah man that sucks but still automating 50 swipes every 6 hours is cool.

**Comment by Darkcast** [comment]
> Great! .. Share it with me :)

I cant send them to you right now but you can download them, I added you to the project.

**Comment by hista** [comment]
> > Great thank you also, I made some changes to the script so it uses a list of cheese pick up lines joy
> 
> I think, my script now no ore working. Because of the website response code changed.

Hi, could you find a fix? Your script was awsome!

**Comment by crazywifi** [comment]
> > > Great thank you also, I made some changes to the script so it uses a list of cheese pick up lines joy
> > 
> > 
> > I think, my script now no ore working. Because of the website response code changed.
> 
> Hi, could you find a fix? Your script was awsome!

Bro gives me some time.

**Comment by crazywifi** [comment]
> > > Great thank you also, I made some changes to the script so it uses a list of cheese pick up lines joy
> > 
> > 
> > I think, my script now no ore working. Because of the website response code changed.
> 
> Hi, could you find a fix? Your script was awsome!

Script version is updated, please check. I am closing this issue.

**Comment by hista** [comment]
Thanks I'm going to try it.
Could you please explain how to get the value of Cookie1 and Cookie2?

**Comment by Exoata** [comment]
> Thanks I'm going to try it.
> Could you please explain how to get the value of Cookie1 and Cookie2?

Same problem. How you did?
