### ISSUE TITLE
How to get cookie1 and cookie2?

### ISSUE THREAD

**Issue by Exoata** [crazywifi/OKCupid_LIKES_Restriction_Bypass#3]
Hello,
I can't get cookie1 and cookie2, or i did somethings wrong. Can you help me?
![image](https://user-images.githubusercontent.com/41582127/73989665-a0fae100-4957-11ea-800e-5e6b3d816559.png)
When i run .py and entered count, nothing. Just waiting like this image.
Kind regards.

**Comment by crazywifi** [comment]
> Hello,
> I can't get cookie1 and cookie2, or i did somethings wrong. Can you help me?
> ![image](https://user-images.githubusercontent.com/41582127/73989665-a0fae100-4957-11ea-800e-5e6b3d816559.png)
> When i run .py and entered count, nothing. Just waiting like this image.
> Kind regards.

You will get a cookie using burp after login but yesterday I check this script and again it stops working because the developer changing the response of the website. I will modify it and update it soon.

**Comment by Exoata** [comment]
> > Hello,
> > I can't get cookie1 and cookie2, or i did somethings wrong. Can you help me?
> > ![image](https://user-images.githubusercontent.com/41582127/73989665-a0fae100-4957-11ea-800e-5e6b3d816559.png)
> > When i run .py and entered count, nothing. Just waiting like this image.
> > Kind regards.
> 
> You will get a cookie using burp after login but yesterday I check this script and again it stops working because the developer changing the response of the website. I will modify it and update it soon.

Thank you will wait.

**Comment by andrewiassur** [comment]
it looks like i have the same issue

**Comment by crazywifi** [comment]
> it looks like i have the same issue

I checked and found that the response of the website changed that is why we are not getting proper response and developer continuously changing the response. So guys, use normal like or make your script by taking reference from this code. Sorry guys. I don't have enough time to make it again.
